---
repos:
- github_repo: testobsessed/docs-content-public
  directory: sectiona
- github_repo: testobsessed/docs-content-private
  directory: sectionb

public_host: mydocs.cfapps.io

template_variables:
  app_domain: example.com
